sudo: required

services:
  - docker

env:
  - VERSION=2.12.2
  - VERSION=2.12.1
  - VERSION=2.12.0
  - VERSION=2.11.11
  - VERSION=2.11.10
  - VERSION=2.11.9
  - VERSION=2.11.8
  - VERSION=2.10.6
  - VERSION=2.10.5
  - VERSION=2.10.4
  - VERSION=2.10.3

script:
  - docker build --tag image:test ${VERSION}
  - bash tests/scala.sh image:test
  - bash tests/scalac.sh image:test
